version = 2

[plugins."io.containerd.grpc.v1.cri".containerd]
    disable_snapshot_annotations = false
  
[proxy_plugins]
    [proxy_plugins.cvmfs-snapshotter]
        type = "snapshot"
        address = "/tmp/containerd-cvmfs-grpc/containerd-cvmfs-grpc.sock"
    [proxy_plugins.stargz]
        type = "snapshot"
        address = "/tmp/containerd-stargz-grpc/containerd-stargz-grpc.sock"
    [proxy_plugins.soci]
        type = "snapshot"
        address = "/tmp/containerd-soci-grpc/containerd-soci-grpc.sock"
